### ISSUE TITLE
minesk.in / imagelink redirection

### ISSUE THREAD

**Issue by xknat** [MineSkin/api.mineskin.org#162]
**Is your feature request related to a problem? Please describe.**
We have a a lot of players from SkinsRestorer that want to apply skins from `http://novask.in`.
This fails as it will redirect to `http://lh3.googleusercontent.com/`

Example: `http://novask.in/747913458.png`

**Describe the solution you'd like**
A way that mineskin can catch the redirection and collect the skin from there.
A way for mineskin to collect a skin from a non.png link like:
`http://lh3.googleusercontent.com/f7E3jItJPMnGRXeho8u-6KQXPsZk-vMZm1p4K9RnxIxVJezQZlzloo_q61RMlV3K8cnI1whmDD9MrutO4lGcfQ`

**Describe alternatives you've considered**
We now have them upload the skin to imgur.
But it would be nice if this process can be done on mineskin side.

**Additional context**
SkinsRestorer = https://github.com/SkinsRestorer/SkinsRestorerX
How we intergrate mineskin = https://github.com/SkinsRestorer/SkinsRestorerX/blob/master/src/main/java/skinsrestorer/shared/utils/MineSkinAPI.java

**Comment by InventivetalentDev** [comment]
mineskin should usually handle redirects to images files just fine and I just tried a couple from novaskin and they were generated properly. so not sure why you're experiencing issues with that.

**Comment by xknat** [comment]
It seems to be that these request do time out for me atleast.
While for a imgur link, its around 600*ms

https://reqbin.com/ also confirms this:
![image](https://user-images.githubusercontent.com/10220139/81023010-6843a880-8e6f-11ea-86a0-d4835cd81d31.png)
![image](https://user-images.githubusercontent.com/10220139/81023038-78f41e80-8e6f-11ea-92f3-afe4cd00b83c.png)

**Comment by InventivetalentDev** [comment]
Okay, I think fixing this should be just as simple as switching to another service for testing requests and increasing the request timeout.  
I've recently made some changes to how mineskin makes requests to mojang's APIs after the recent issues with mismatching textures and requests being blocked by mojang, which also included a bit of longer generation time.  
  
It looks like reqbin has a fixed timeout on their end, so it just stops the request entirely if there's no data returned within that timeout. If you send another request with the same URL a few seconds later, it will return the data just fine since it was generated in the background (but never had a chance to send anything back due to the timeout).   
  
For testing I'd recommend installing [Postman](https://www.postman.com/) locally & in your request code increase the maximum timeout to like 30 seconds.  
It's a lot. I know. I'm just trying to keep things from breaking at the moment, might be faster again in the future.
