### ISSUE TITLE
An endpoint that only generates data for the skin, but does not upload it.

### ISSUE THREAD

**Issue by Revxrsal** [MineSkin/api.mineskin.org#209]
**Is your feature request related to a problem? Please describe.**
Perhaps it is. I am likely to use this API a lot and would like to avoid overloading it. I am mainly using it to convert skin images to data which contains signature and whatnot, and believe that uploading it would be deemed unnecessary.

**Describe the solution you'd like**
A simple endpoint that takes the skin file as an input and outputs the data. Does not store the image or skin data.

**Describe alternatives you've considered**
I can just use the /generate/upload endpoint to get what I want.

**Additional context**
Example response:
```json
{
  "model": "steve",
  "data": {
    "uuid": "3d7834c2-9543-4f13-9bcf-f9a14a35e2ec",
    "texture": {
      "value": "...",
      "signature": "..."
    }
  },
  "timestamp": 1606936920
}
```

**Comment by InventivetalentDev** [comment]
The images are uploaded to mojang's servers in order to get a valid `value` and `signature` by logging into mineskin's accounts and updating their skins. So the skins do need to be uploaded, or you won't be able to get valid texture data back.  

Don't worry about overloading the API. There are enough rate limits & caches which should prevent any issues. Mojang themself also have their own rate limiting which needs to be respected by mineskin, hence the somewhat long generation times. So if you're planning on using this API a lot, you should also make sure to have enough delays between requests to avoid any issues.  

And if you're concerned about others being able to  view your skin data, just send the  `visibility` param as private and it won't show up in the gallery pages :) https://github.com/MineSkin/api.mineskin.org/wiki/REST-API#generate---parameters--response

**Comment by Revxrsal** [comment]
Thank you for the quick reply.

And thanks for the clarification. I'll make sure to donate once I publish my project to support this robust API. :)
