### ISSUE TITLE
Incorrect model returns 500 | Format Detection

### ISSUE THREAD

**Issue by mergu** [MineSkin/api.mineskin.org#29]
I noticed that specifying the incorrect player model for a provided url fails. I'm not sure if this is an issue with this api or with mojang, but I do know the minecraft launcher allows you to set either model and might distort the skin to fit. Would be great if that functionality was here too, instead of just breaking.

For example,
```
curl -X POST "https://api.mineskin.org/generate/url?model=slim" -d "url=https://i.imgur.com/Pgu9R1s.png"
```
will always return
```
{"error":"Failed to generate skin data","err":"Authentication failed - Invalid credentials. Invalid username or password.","accountId":#}
```

**Comment by InventivetalentDev** [comment]
huh, so it works if you use the default model?

**Comment by mergu** [comment]
Yup it does

**Comment by ajgeiss0702** [comment]
Please fix this

**Comment by InventivetalentDev** [comment]
This isn't really a priority since additionally checking the image data for the skin type is gonna require additional server resources and probably won't be 100% reliable either.  
The error message from the original issue is returned by mojang's API (and obviously doesn't give much info), so it'll keep returning 500s for now.

**Comment by mergu** [comment]
As far as I can tell, this seems to be fixed. A texture is generated for the correct model regardless of how you call the api.
